version: 2.1

orbs:
  cfa: continuousauth/npm@2.1.0
  node: electronjs/node@2.2.3

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test:
          name: test-<< matrix.executor >>-<< matrix.node-version >>
          pre-steps:
            - run: git config --global core.autocrlf input
          matrix:
            alias: test
            parameters:
              executor:
                - node/linux
                - node/macos
                - node/windows
              node-version:
                - '22.1'
                - '20.10'
                - '18.18'
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
