version: 2.1

orbs:
  cfa: continuousauth/npm@1.0.2
  node: circleci/node@5.1.0
  win: circleci/windows@5.0.0

commands:
  install:
    parameters:
      node-version:
        description: Node.js version to install
        type: string
    steps:
      - run: git config --global core.autocrlf input
      - node/install:
          node-version: << parameters.node-version >>
      - run: nvm use << parameters.node-version >>
      # Can't get yarn installed on Windows with the circleci/node orb, so use npx yarn for commands
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run: npx yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

jobs:
  test-linux:
    docker:
      - image: cimg/base:stable
    parameters:
      node-version:
        description: Node.js version to install
        type: string
    steps:
      - install:
          node-version: << parameters.node-version >>
      - run: npx yarn test
  test-mac:
    macos:
      xcode: "13.0.0"
    resource_class: macos.x86.medium.gen2
    parameters:
      node-version:
        description: Node.js version to install
        type: string
    steps:
      - install:
          node-version: << parameters.node-version >>
      - run: npx yarn test
  test-windows:
    executor:
      name: win/default
      shell: bash.exe
    parameters:
      node-version:
        description: Node.js version to install
        type: string
    steps:
      - install:
          node-version: << parameters.node-version >>
      - run: npx yarn test

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test-linux:
          matrix:
            parameters:
              node-version:
                - 18.14.0
                - 16.19.0
                - 14.19.0
      - test-mac:
          matrix:
            parameters:
              node-version:
                - 18.14.0
                - 16.19.0
                - 14.19.0
      - test-windows:
          matrix:
            parameters:
              node-version:
                - 18.14.0
                - 16.19.0
                - 14.19.0
      - cfa/release:
          requires:
            - test-linux-18.14.0
            - test-linux-16.19.0
            - test-linux-14.19.0
            - test-mac-18.14.0
            - test-mac-16.19.0
            - test-mac-14.19.0
            - test-windows-18.14.0
            - test-windows-16.19.0
            - test-windows-14.19.0
          filters:
            branches:
              only:
                - main
          context: cfa-release
